### PR TITLE
Do not publish src folder and useless files

### LINKED ISSUE #28: Do not publish src folder and useless files!
Current content of archive v4.0.0

```
npm notice === Tarball Contents === 
npm notice 1.3kB  package.json                       
npm notice 5.2kB  CHANGELOG.md                       
npm notice 186B   codecov.yml                        
npm notice 557B   copy-proto                         
npm notice 11.3kB LICENSE                            
npm notice 10.0kB logo.svg                           
npm notice 8.5kB  README.md                          
npm notice 535B   tsconfig-istanbul.json             
npm notice 508B   tsconfig.json                      
npm notice 387B   .circleci/config.yml               
npm notice 232B   .github/main.workflow              
npm notice 132B   lib/api/index.d.ts                 
npm notice 1.9kB  lib/api/index.js                   
npm notice 1.7kB  lib/api/index.js.map               
npm notice 609B   lib/api/mock.d.ts                  
npm notice 2.2kB  lib/api/mock.js                    
npm notice 2.1kB  lib/api/mock.js.map                
npm notice 4.9kB  lib/api/types.d.ts                 
npm notice 577B   lib/api/types.js                   
npm notice 269B   lib/api/types.js.map               
npm notice 636B   lib/application/application.d.ts   
npm notice 2.4kB  lib/application/application.js     
npm notice 1.7kB  lib/application/application.js.map 
npm notice 221B   lib/application/index.d.ts         
npm notice 508B   lib/application/index.js           
npm notice 433B   lib/application/index.js.map       
npm notice 107B   lib/index.d.ts                     
npm notice 276B   lib/index.js                       
npm notice 173B   lib/index.js.map                   
npm notice 1.3kB  lib/protobuf/api/core.proto        
npm notice 1.4kB  lib/protobuf/api/event.proto       
npm notice 2.5kB  lib/protobuf/api/execution.proto   
npm notice 2.0kB  lib/protobuf/api/instance.proto    
npm notice 2.4kB  lib/protobuf/api/service.proto     
npm notice 448B   lib/protobuf/types/event.proto     
npm notice 1.6kB  lib/protobuf/types/execution.proto 
npm notice 217B   lib/protobuf/types/instance.proto  
npm notice 3.6kB  lib/protobuf/types/service.proto   
npm notice 177B   lib/service/index.d.ts             
npm notice 645B   lib/service/index.js               
npm notice 582B   lib/service/index.js.map           
npm notice 725B   lib/service/service.d.ts           
npm notice 6.1kB  lib/service/service.js             
npm notice 2.4kB  lib/service/service.js.map         
npm notice 793B   lib/util/grpc.d.ts                 
npm notice 1.2kB  lib/util/grpc.js                   
npm notice 1.0kB  lib/util/grpc.js.map               
npm notice 2.8kB  src/api/index.ts                   
npm notice 1.7kB  src/api/mock.ts                    
npm notice 4.2kB  src/api/types.ts                   
npm notice 4.2kB  src/application/application_test.ts
npm notice 1.9kB  src/application/application.ts     
npm notice 405B   src/application/index.ts           
npm notice 108B   src/index.ts                       
npm notice 1.3kB  src/protobuf/api/core.proto        
npm notice 1.4kB  src/protobuf/api/event.proto       
npm notice 2.5kB  src/protobuf/api/execution.proto   
npm notice 2.0kB  src/protobuf/api/instance.proto    
npm notice 2.4kB  src/protobuf/api/service.proto     
npm notice 448B   src/protobuf/types/event.proto     
npm notice 1.6kB  src/protobuf/types/execution.proto 
npm notice 217B   src/protobuf/types/instance.proto  
npm notice 3.6kB  src/protobuf/types/service.proto   
npm notice 532B   src/service/index.ts               
npm notice 3.8kB  src/service/service_test.ts        
npm notice 2.5kB  src/service/service.ts             
npm notice 670B   src/util/grpc_test.ts              
npm notice 1.9kB  src/util/grpc.ts    
```

### PR DESCRIPTION
**Pull request by Roms1383**
Fixed #28
Packaging can be tested with `npm run lerna exec -- npm pack`
Do not hesitate to come back to me if ever you have additional requirements concerning the packaged files.

### CODE REVIEW

**Comment by antho1404** [comment]
Could you update the changelog on the different packages please :)

**Comment by antho1404** [comment]
The library `@mesg/compiler` has been added, can you make sure that you checked this one too 🙏

**Comment by Roms1383** [comment]
Please update the base branch and CI result in Github Actions.

**Comment by Roms1383** [comment]
I'm testing right now and so far it failed because of the `build` script in **compiler** package.
Still investigating.

**Comment by Roms1383** [comment]
Ok my bad I forget to `install` the new package first, actually it works.

**Review by antho1404 — APPROVED** [review]

**Comment by antho1404** [comment]
Thanks for that, I will release a new version today to include this :)

**Pull request merged**
